//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaChessV2.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyHistory
    {
        public int Id { get; set; }
        public int FK_Party { get; set; }
        public string Board { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
