//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaChess.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMove
    {
        public int Id { get; set; }
        public int FK_Party { get; set; }
        public System.DateTime MoveDate { get; set; }
        public string Move { get; set; }
        public int MoveNumber { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
