//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaChess.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.PartyMoves = new HashSet<PartyMove>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string WhiteLink { get; set; }
        public string BlackLink { get; set; }
        public string PartLink { get; set; }
        public int FK_Board_Type { get; set; }
        public string Board { get; set; }
        public bool WhiteTurn { get; set; }
        public string Seed { get; set; }
    
        public virtual Board BoardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyMove> PartyMoves { get; set; }
    }
}
